name: ' CI/CD'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
      - '!.github/workflows/CICD.yaml'
    branches: [ 'main' ]

defaults:
  run:
    shell: pwsh

permissions:
  actions: read
  contents: read
  id-token: write
  packages: read

env:
  workflowDepth: 1
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ ubuntu-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
      projects: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
      skippedProjects: ${{ steps.determineProjectsToBuild.outputs.SkippedProjectsJson }}
      projectDependenciesJson: ${{ steps.determineProjectsToBuild.outputs.ProjectDependenciesJson }}
      buildOrderJson: ${{ steps.determineProjectsToBuild.outputs.BuildOrderJson }}
      baselineWorkflowRunId: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowRunId }}
      baselineWorkflowSHA: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowSHA }}
      workflowDepth: ${{ steps.DetermineWorkflowDepth.outputs.WorkflowDepth }}
      trackALAlertsInGitHub: ${{ steps.SetALCodeAnalysisVar.outputs.trackALAlertsInGitHub }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v9.0
        with:
          shell: pwsh

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v9.0
        with:
          shell: pwsh
          get: type,useGitSubmodules,trackALAlertsInGitHub

      - name: Set AL Code Analysis Var output
        id: SetALCodeAnalysisVar
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "trackALAlertsInGitHub=$($env:trackALAlertsInGitHub)"

      - name: Determine Workflow Depth
        id: DetermineWorkflowDepth
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "WorkflowDepth=$($env:workflowDepth)"

      - name: Determine Projects To Build
        id: determineProjectsToBuild
        uses: microsoft/AL-Go-Actions/DetermineProjectsToBuild@v9.0
        with:
          shell: pwsh
          maxBuildDepth: ${{ env.workflowDepth }}

  Build:
    needs: [ Initialization ]
    if: (!failure()) && (!cancelled()) && fromJson(needs.Initialization.outputs.buildOrderJson)[0].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[0].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ matrix.githubRunnerShell }}
      runsOn: ${{ matrix.githubRunner }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      skippedProjectsJson: ${{ needs.Initialization.outputs.skippedProjects }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      baselineWorkflowRunId: ${{ needs.Initialization.outputs.baselineWorkflowRunId }}
      baselineWorkflowSHA: ${{ needs.Initialization.outputs.baselineWorkflowSHA }}
      secrets: 'appDependencySecrets'
      useArtifactCache: true
      needsContext: ${{ toJson(needs) }}

  CodeAnalysisUpload:
    needs: [ Initialization, Build ]
    if: (!cancelled()) && (needs.Initialization.outputs.trackALAlertsInGitHub == 'True')
    runs-on: [ ubuntu-latest ]
    name: Code Analysis Processing
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download artifacts - ErrorLogs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: (success() || failure())
        with:
          pattern: '*-*ErrorLogs-*'
          path: '${{ github.workspace }}/ErrorLogs/'
          merge-multiple: true

      - name: Process AL Code Analysis Logs
        id: ProcessALCodeAnalysisLogs
        if: (success() || failure())
        uses: microsoft/AL-Go-Actions/ProcessALCodeAnalysisLogs@v9.0
        with:
          shell: pwsh

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v4
        if: (success() || failure()) && (hashFiles(format('{0}/ErrorLogs/output.sarif.json',github.workspace)) != '')
        with:
          sarif_file: '${{ github.workspace }}/ErrorLogs/output.sarif.json'
          category: "ALCodeAnalysis"
